/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.gipmbh.gradle.plugins.release

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'de.gipmbh.gradle.plugins.release.greeting' plugin.
 */
class GipReleasePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("gip-release-new")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
